// ============================================
// mobile/src/screens/orders/OrderSuccessScreenPremiumStyles.js
// ============================================
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  'order-success-premium-screen': {
    flex: 1,
    backgroundColor: '#F5F7FA',
    padding: 24,
    justifyContent: 'center',
  },
  'order-success-premium-animation': {
    alignItems: 'center',
    marginBottom: 32,
  },
  'order-success-premium-circle': {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  'order-success-premium-circle-inner': {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  'order-success-premium-title': {
    fontSize: 28,
    fontWeight: '800',
    color: '#1A1A1A',
    textAlign: 'center',
    marginBottom: 8,
  },
  'order-success-premium-subtitle': {
    fontSize: 16,
    color: '#4A4A4A',
    textAlign: 'center',
    marginBottom: 32,
    fontWeight: '500',
  },
  'order-success-premium-details-card': {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  'order-success-premium-detail-row': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  'order-success-premium-detail-label': {
    fontSize: 15,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  'order-success-premium-detail-value': {
    fontSize: 15,
    color: '#1A1A1A',
    fontWeight: '700',
  },
  'order-success-premium-detail-value-highlight': {
    fontSize: 22,
    color: '#0A84FF',
    fontWeight: '800',
  },
  'order-success-premium-payment-badge': {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(94, 92, 230, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  'order-success-premium-divider': {
    height: 1,
    backgroundColor: '#F5F7FA',
  },
  'order-success-premium-delivery-info': {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 132, 255, 0.08)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(10, 132, 255, 0.15)',
  },
  'order-success-premium-delivery-icon-wrapper': {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  'order-success-premium-delivery-info-text': {
    flex: 1,
  },
  'order-success-premium-delivery-info-title': {
    fontSize: 13,
    color: '#4A4A4A',
    fontWeight: '500',
    marginBottom: 4,
  },
  'order-success-premium-delivery-info-address': {
    fontSize: 16,
    color: '#1A1A1A',
    fontWeight: '700',
  },
  'order-success-premium-action-buttons': {
    gap: 12,
    marginBottom: 24,
  },
  'order-success-premium-btn-track-order': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A84FF',
    paddingVertical: 18,
    borderRadius: 16,
    gap: 10,
    shadowColor: '#0A84FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  'order-success-premium-btn-track-order-text': {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  'order-success-premium-btn-continue-shopping': {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#0A84FF',
  },
  'order-success-premium-btn-continue-shopping-text': {
    fontSize: 16,
    fontWeight: '700',
    color: '#0A84FF',
  },
  'order-success-premium-help-section': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  'order-success-premium-help-text': {
    fontSize: 14,
    color: '#4A4A4A',
    fontWeight: '500',
  },
});